/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ITLMPack;

/**
 *
 * @author Marina Nik
 */
import java.awt.event.ItemEvent;
import javax.swing.WindowConstants;

public class DBGUI extends javax.swing.JFrame {

    /**
     * Creates new form DBGUI
     */
    public DBGUI(int index) {
        initComponents();
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        //GUI.getBase(ind).tables = new ArrayList<>();
        for (int i = 0; i < GUI.getBase(index).tableNum(); i++){
            TableComboBox.addItem(GUI.getBase(index).getTableInOrder(i).name);
            AComboBox.addItem(GUI.getBase(index).getTableInOrder(i).name);
            BComboBox.addItem(GUI.getBase(index).getTableInOrder(i).name);
            revalidate();
            repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreateButton = new javax.swing.JButton();
        TableComboBox = new javax.swing.JComboBox<>();
        MultButton = new javax.swing.JButton();
        AComboBox = new javax.swing.JComboBox<>();
        XLabel = new javax.swing.JLabel();
        BComboBox = new javax.swing.JComboBox<>();
        GoToButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        ReturnButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        InfoPane = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CreateButton.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        CreateButton.setText("Створити таблицю");
        CreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonActionPerformed(evt);
            }
        });

        TableComboBox.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        TableComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TableComboBoxItemStateChanged(evt);
            }
        });

        MultButton.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        MultButton.setText("Прямий добуток:");
        MultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultButtonActionPerformed(evt);
            }
        });

        AComboBox.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        XLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        XLabel.setText("X");

        BComboBox.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        GoToButton.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        GoToButton.setText("Перейти");
        GoToButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoToButtonActionPerformed(evt);
            }
        });

        EditButton.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        EditButton.setText("Редагувати");
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });

        DeleteButton.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        DeleteButton.setText("Видалити");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        ReturnButton.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ReturnButton.setText("Повернутися до вибору бази");
        ReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnButtonActionPerformed(evt);
            }
        });

        InfoPane.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(InfoPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CreateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(TableComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GoToButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReturnButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MultButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(XLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BComboBox)
                    .addComponent(XLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AComboBox)
                    .addComponent(MultButton, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(CreateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TableComboBox)
                    .addComponent(GoToButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EditButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ReturnButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonActionPerformed
        // TODO add your handling code here:
        InfoPane.setText(inp);
        BaseDialog.main(true, dbInd, GUI.getBase(dbInd).tableNum());
    }//GEN-LAST:event_CreateButtonActionPerformed

    private void MultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultButtonActionPerformed
        // TODO add your handling code here:
        if (AComboBox.getSelectedItem() == null || BComboBox.getSelectedItem() == null)
            InfoPane.setText(inp + "\n\nБаза має містити хоча б дві таблиці!");
        else{
            int fst = 0;
            int snd = 0;
            for (int i = 0; i < GUI.getBase(dbInd).tableNum(); i++){
                if (GUI.getBase(dbInd).getTableInOrder(i).name.equals(AComboBox.getSelectedItem()))
                    fst = GUI.getBase(dbInd).getTableInOrder(i).getIndex();
                if (GUI.getBase(dbInd).getTableInOrder(i).name.equals(BComboBox.getSelectedItem()))
                    snd = GUI.getBase(dbInd).getTableInOrder(i).getIndex();
            }
            if (fst == snd){
                InfoPane.setText(inp + "\n\nТаблиці мають бути різними!");
            }
            else{
                Table tab = GUI.getBase(dbInd).union(fst, snd);
                addComponent(tab);
                validate();
                setVisible(true);
            }
        }
    }//GEN-LAST:event_MultButtonActionPerformed

    private void GoToButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoToButtonActionPerformed
        // TODO add your handling code here:
        if (isGUIActive){
            InfoPane.setText(inp + "\n\nОдночасно можна відкрити тільки одну таблицю!!");
        }
        else if (GUI.getBase(dbInd).tableNum() == 0){
            InfoPane.setText(inp + "\n\nБаза має містити хоча б одну таблицю!");
        }
        else{
            isGUIActive = true;
            TGUI.main(dbInd, curTable.getIndex());
        }
    }//GEN-LAST:event_GoToButtonActionPerformed

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        // TODO add your handling code here:
        if (isGUIActive){
            InfoPane.setText(inp + "\n\nОдночасно можна відкрити тільки одну таблицю!!");
        }
        else if (GUI.getBase(dbInd).tableNum() == 0){
            InfoPane.setText(inp + "\n\nБаза має містити хоча б одну таблицю!");
        }
        else{
            BaseDialog.main(false, dbInd, curTable.getIndex());
        }
    }//GEN-LAST:event_EditButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        if (isGUIActive){
            InfoPane.setText(inp + "\n\nОдночасно можна відкрити тільки одну таблицю!!");
        }
        else if (GUI.getBase(dbInd).tableNum() == 0){
            InfoPane.setText(inp + "\n\nБаза має містити хоча б одну таблицю!");
        }
        else{
            TableComboBox.removeAllItems();
            AComboBox.removeAllItems();
            BComboBox.removeAllItems();
            validate();
            repaint();
            GUI.getBase(dbInd).delT(curTable.getIndex());
            for (int i = 0; i < GUI.getBase(dbInd).tableNum(); i++){
                TableComboBox.addItem(GUI.getBase(dbInd).getTableInOrder(i).name);
                AComboBox.addItem(GUI.getBase(dbInd).getTableInOrder(i).name);
                BComboBox.addItem(GUI.getBase(dbInd).getTableInOrder(i).name);
            }
            validate();
            repaint();
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void TableComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TableComboBoxItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED){
            String temp = TableComboBox.getSelectedItem().toString();
            for (int i = 0; i < GUI.getBase(dbInd).tableNum(); i++)
                if (GUI.getBase(dbInd).getTableInOrder(i).name.equals(temp)){
                    curTable = GUI.getBase(dbInd).getTableInOrder(i);
                    break;
                }
            InfoPane.setText(inp + "\n\nТаблиця\nНазва: " + curTable.name + "\nКількість рядків: " + curTable.rowNum()
                    + "\nКількість стовпців: " + curTable.attrNum() + "\nНомер: " + curTable.getIndex());
        }
    }//GEN-LAST:event_TableComboBoxItemStateChanged

    private void ReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnButtonActionPerformed
        // TODO add your handling code here:
        if (isGUIActive){
            InfoPane.setText(inp + "\n\nЗакрийте відкриті таблиці!");
        }
        else{
            isGUIActive = false;
            GUI.disableGUI(false);
            dispose();
        }
    }//GEN-LAST:event_ReturnButtonActionPerformed

    public static int getDBInd(){
        return dbInd;
    }
    
    public static void addComponent(Table t){
        TableComboBox.addItem(t.name);
        AComboBox.addItem(t.name);
        BComboBox.addItem(t.name);
    }
    
    public static void replaceItems(){
        TableComboBox.removeAllItems();
        AComboBox.removeAllItems();
        BComboBox.removeAllItems();
        for (int i = 0; i < GUI.getBase(dbInd).tableNum(); i++){
            TableComboBox.addItem(GUI.getBase(dbInd).getTable(i).name);
            AComboBox.addItem(GUI.getBase(dbInd).getTable(i).name);
            BComboBox.addItem(GUI.getBase(dbInd).getTable(i).name);
        }
    }
    
    public static void removeComponent(String name){
        for (int i = 0; i < GUI.getBase(dbInd).tableNum(); i++)
            if (GUI.getBase(dbInd).getTable(i).name.equals(name)){
                TableComboBox.remove(i);
                AComboBox.remove(i);
                BComboBox.remove(i);
                break;
            }
    }
    
    public static void disableGUI(boolean contr){
        isGUIActive = contr;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(int index) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DBGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DBGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DBGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DBGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DBGUI(index).setVisible(true);
                inp = "База даних:\nНазва: " + GUI.getBase(index).name + "\nОпис: "
                    + GUI.getBase(index).descript + "\nНомер: " + GUI.getBase(index).getIndex();
                InfoPane.setText(inp);
                dbInd = index;
            }
        });
    }

    private static String inp = ""; 
    
    private static int dbInd;
    
    private static Table curTable;
    
    private static boolean isGUIActive = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JComboBox<String> AComboBox;
    private static javax.swing.JComboBox<String> BComboBox;
    private javax.swing.JButton CreateButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton EditButton;
    private javax.swing.JButton GoToButton;
    private static javax.swing.JTextPane InfoPane;
    private javax.swing.JButton MultButton;
    private javax.swing.JButton ReturnButton;
    private static javax.swing.JComboBox<String> TableComboBox;
    private javax.swing.JLabel XLabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
